version: '3.8'
services:
  db:
    image: itsnotrohit/docker-webapp-mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password

  mcache:
    image: memcached
    ports:
      - "11211:11211"

  rmq:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    image: itsnotrohit/docker-webapp-tomcat
    ports:
      - "8080:8080"
    volumes: 
      - appdata:/usr/local/tomcat/webapps

  web:
    image: itsnotrohit/docker-webapp-nginx
    ports:
      - "80:80"

volumes:
  dbdata: {}
  appdata: {}