services:
  db:
    image: itsnotrohit/webapp-mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5

  mcache:
    image: memcached
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD", "echo", "stats", "|", "nc", "localhost", "11211"]
      interval: 20s
      timeout: 5s
      retries: 5

  rmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 5s
      retries: 5

  app:
    image: itsnotrohit/webapp-tomcat
    ports:
      - "8080:8080"
    volumes: 
      - appdata:/usr/local/tomcat/webapps
    depends_on:
      db:
        condition: service_healthy
      mcache:
        condition: service_healthy
      rmq:
        condition: service_healthy

  web:
    image: itsnotrohit/webapp-nginx
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started

volumes:
  dbdata: {}
  appdata: {}
